// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA377LfexSVPDKbN4BUcGsBaJUUJi3ve4g',
    appId: '1:203536738767:web:d7d380623b193d5ba5caba',
    messagingSenderId: '203536738767',
    projectId: 'bountie-23026',
    authDomain: 'bountie-23026.firebaseapp.com',
    storageBucket: 'bountie-23026.appspot.com',
    measurementId: 'G-GNSL4QQ7SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7qMv2N0rks5h27mb-TGUrV_Rsm-2FR4M',
    appId: '1:203536738767:android:8e52dc0cab076d62a5caba',
    messagingSenderId: '203536738767',
    projectId: 'bountie-23026',
    storageBucket: 'bountie-23026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDESki_ffoGPdnSfGYnimlrS2i6Z6577oA',
    appId: '1:203536738767:ios:cd815b44ce70222fa5caba',
    messagingSenderId: '203536738767',
    projectId: 'bountie-23026',
    storageBucket: 'bountie-23026.appspot.com',
    iosBundleId: 'com.example.bountie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDESki_ffoGPdnSfGYnimlrS2i6Z6577oA',
    appId: '1:203536738767:ios:f5c5bb05af980b82a5caba',
    messagingSenderId: '203536738767',
    projectId: 'bountie-23026',
    storageBucket: 'bountie-23026.appspot.com',
    iosBundleId: 'com.example.bountie.RunnerTests',
  );
}
